name: "t1action-tarea"
description: "A GitHub Action to run Tarea tasks"
inputs:
  name:
    description: "The name of the task to run"
    required: true         
runs:    
  using: "node20"
  main: "dist/index.js"
  