name: workflowt1action
on:
  workflow_dispatch:
jobs:
  t1workflow:  # Repo t1workflow - privado'
    runs-on: ubuntu-latest
    environment: ${{github.ref_name == 'develop' && 'dev'  || github.ref_name == 'release' && 'qa' || github.ref_name == 'main' && 'prod'}}
    steps:  # BEGIN:
      - name: t1action-tarea
        id: t1action-tarea
        env:
          MAYORIA_EDAD: 18            
        run: |
           EDAD_ACTUAL=${{vars.EDAD}}
           TIEMPO=$((EDAD_ACTUAL - MAYORIA_EDAD))
           
           if [ $TIEMPO -gt 0 ]; then
              echo "${{vars.NOMBRE}} ${{vars.APELLIDO}} cumplio la mayoria de edad hace $TIEMPO años"
              
            else  
              echo "${{vars.NOMBRE}} ${{vars.APELLIDO}} aun no cumple la mayoria de edad"
              
            fi
           
